language: python
sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
python: "3.7"
cache: pip

env:
  global:
    secure: GYWORGegczM/4Nuir8nOh5PHQkAONDuwqIIcJIFE1v32DpIAhIocEX5MuZ/a5A+0bcBg63D4tJDE58ZIhFzKeAzmky4rkSlfmDUyE/vKe6Rr2C9NBGrO7mlTpUrEPkxIRAjQq1q4oHJEkKoXZRd/Sv3Zcs0sYjO9xJhOErEn4Sp2Yn4Qs62Ibvu9yR3mKZ3529k58kVX7iPSsQWIzpYWAQfOeap2Pjts6WuB1O/Gec40jiQ8VyTO+IC9vfH5txX3epkk2vRwra3IQ6RNRqblAXVRlg7LRLi9NUOQyBXfl36OsJ3jg2X+kS3xp5AO9Cz3ZOGiJx1pGNpyrfIKVFXdMaQHjR+9QDhFK2VC9j2RYqTlrK1yVrganlfSSJ3+U/OhjBGIakPYTj4ncJ+OPcyaycnqtGbBrAo5Xza5u9++9S94Qa6KFn/sZEs9y/K9rWggV5y2fZgJa2x6poZKwV3aVJTLeF8FgcvnHwdZuFRaQJ2WqXWuEunYAW3Ov3Ipws4OO9+6Zgb4XahV2o//IMzCWj0z4L7M8qLFu8MgqP41YiV6tHE550cH5WK+XF2PNN7MpVZLaOb28K/zUO4hMHfFuBXmbAgXMjIapxpTm5ab1lG0IVVg1weE81smqDoAOqnUYum3tTIdkBrmxoUnk5zlFaDLZvbGkyvJ7r4GaSgrP6Q=
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install flake8
before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 manimlib/ --count --select=E9,F63,F72,F82 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 manimlib/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
  - python setup.py test
  - python setup.py bdist_wheel
after_success:
  - openssl aes-256-cbc -K $encrypted_1b28e850a424_key -iv $encrypted_1b28e850a424_iv -in travis/crypt.enc -out travis/crypt -d
  - tar xf travis/crypt
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && travis/deploy_docs.sh
deploy:
  provider: pypi
  user: eulertour
  on:
    tags: true
  password:
    secure: j5M2hiJo9kDWJhl0/iSuIQmfd2G2O1Qoc455AkUPMCheAcALnX9xJgFsYBmqfgOXTCtUCQf52XGdOIG4o4s5TY340NZ9eLKI9cWae+sTeSrDCkdwChUilm3D0jQf1FWPUf9ywScwGi20m0sRtzxEJyTuX+JMFd7PIa8bFoDXWPtEjoFOOJrfBusMsANzrI+j+vIMdJ48lc1J8UsQdZapwusTrYU9s12JLhKBPLavmaDKf0HDAJdEhFQ9SaINdkiW/QY8qbfJ/MVu5jHai168zXjD/IaswxoKqCO1G+fWlOq3KwVhG7gI7rwhnnuF+wcA7yLAaMdo0CjO2V7z15S6cG721V2Il2IIh1jq0F8irSH1ZOLOkv/fFk9hkSUQyEU0i8k4m1wE9L47a6GP/66+b+gI91PGfxBOqq4gE/1BdZJqceh0qc13KpcehtYrQwR05bSw0Ye5OoTkqAnCeON0B0Ur4ejfHd3TzkjgB06fw76cZtjAK8f/YjB3KyNCvysOixgzE4tRxlY92yX/tAKZ3iX3yD0MjsinSfwo52N5sIEaCS/FmPRMhJOQBa6ftkfbcUNQBTG9G3b134XXF/LbC4vBloCaTm5VSXagta+oY3SFKQxPAZXx7X+wcFGjqxDjZXG1e66QnA2JJH4aBDsRfSXmUtD8MblwFYdcCJWz+Ck=
